name: Run Test Case

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: clear
      run: dotnet clean --configuration Debug && dotnet nuget locals all --clear
    - name: Build with dotnet
      run: dotnet build --configuration Debug
    - name: Run Test Case
      run: cd test/ & test
      shell: cmd
